import { MoonbirdConfig } from './assemble';

const layerOptions = {
    backgrounds: ['Gray', 'Lilac','Light Red','Light Green','Light Yellow','Jade', 'Cosmic', 'Enlightened'],
    bodies: ['Crescent - Alien', 'Sprite - Pink', 'Sprite - Purple', 'Sprite - Red', 'Sprite - Black', 'Sprite - Blue', 'Sprite - Brown', 'Sprite - Gray', 'Sprite - White', 'Sprite - Green', 'Great Horned Skeleton', 'Horned Skeleton', 'Robot - Evo', 'Robot - MKVII', 'Brave - Black', 'Brave - Blue', 'Brave - Brown', 'Brave - Gray', 'Brave - Green', 'Brave - Pink', 'Brave - Purple', 'Brave - Red', 'Brave - White', 'Cosmic - Legendary Brave', 'Cosmic - Legendary Crescent', 'Cosmic - Legendary Emperor', 'Cosmic - Legendary Guardian', 'Cosmic - Legendary Professor', 'Cosmic - Legendary Sage', 'Crescent - Black', 'Crescent - Blue', 'Crescent - Brown', 'Crescent - Gray', 'Crescent - Green', 'Crescent - Pink', 'Crescent - Purple', 'Crescent - Red', 'Crescent - White', 'Emperor - Black', 'Emperor - Blue', 'Emperor - Brown', 'Emperor - Gray', 'Emperor - Green', 'Emperor - Pink', 'Emperor - Purple', 'Emperor - Red', 'Emperor - White', 'Enlightened - Legendary Brave', 'Enlightened - Legendary Crescent', 'Enlightened - Legendary Emperor', 'Enlightened - Legendary Guardian', 'Enlightened - Legendary Professor', 'Enlightened - Legendary Sage', 'Glitch2 - Legendary Brave', 'Glitch - Legendary Brave', 'Glitch - Legendary Crescent', 'Glitch - Legendary Emperor', 'Glitch2 - Legendary Guardian', 'Glitch - Legendary Guardian', 'Glitch - Legendary Professor', 'Glitch - Legendary Sage', "Diamond - Legendary Crescent", 'Golden - Legendary Crescent', 'Golden - Legendary Emperor', 'Golden - Legendary Professor', 'Golden - Legendary Sage', 'Guardian - Black', 'Guardian - Blue', 'Guardian - Brown', 'Guardian - Gray', 'Guardian - Green', 'Guardian - Pink', 'Guardian - Purple', 'Guardian - Red', 'Guardian - White', 'Jade - Legendary Brave', 'Jade - Legendary Crescent', 'Jade - Legendary Emperor', 'Jade - Legendary Guardian', 'Jade - Legendary Professor', 'Jade - Legendary Sage', 'Professor - Black', 'Professor - Blue', 'Professor - Brown', 'Professor - Gray', 'Professor - Green', 'Professor - Pink', 'Professor - Purple', 'Professor - Red', 'Professor - White', 'Raincloud', 'Robot - Metal', 'Ruby Skeleton - Legendary Bone', 'Sage - Black', 'Sage - Blue', 'Sage - Brown', 'Sage - Gray', 'Sage - Green', 'Sage - Pink', 'Sage - Purple', 'Sage - Red', 'Sage - White', 'Skeleton - Bone', 'Stark - Black', 'Stark - Blue', 'Stark - Brown', 'Stark - Gray', 'Stark - Green', 'Stark - Pink', 'Stark - Purple', 'Stark - Red', 'Stark - White', 'Tabby - Black', 'Tabby - Blue', 'Tabby - Brown', 'Tabby - Gray', 'Tabby - Green', 'Tabby - Pink', 'Tabby - Purple', 'Tabby - Red', 'Tabby - White', 'Tranquil - Black', 'Tranquil - Blue', 'Tranquil - Brown', 'Tranquil - Gray', 'Tranquil - Green', 'Tranquil - Pink', 'Tranquil - Purple', 'Tranquil - Red', 'Tranquil - White'],
    beaks: ['Small - Alien', 'Small - Pierced', 'Long - Golden', 'Long - Gray', 'Long - Orange', 'Long - Robot', 'Long - Ruby', 'Long - Skeleton', 'Short (Jade)', 'Short - Golden', 'Short - Gray', 'Short - Orange', 'Short - Robot', 'Short - Ruby', 'Short - Skeleton', 'Small (Cosmic)', 'Small (Enlightened)', 'Small (Jade)', 'Small - Golden', 'Small - Gray', 'Small - Orange', 'Small - Robot', 'Small - Ruby', 'Small - Skeleton'],
    eyes: ['Dizzy - Epic', 'Laser - Epic', 'Blue Laser - Epic', 'Alien - Epic', 'Adorable - Epic', 'Adorable - Ruby', 'Angry - Blue', 'Angry - Golden', 'Angry - Gray', 'Angry - Green', 'Angry - Purple', 'Angry - Red', 'Angry - Robot', 'Angry - Ruby', 'Angry - Skeleton', 'Angry - White', 'Angry - Yellow', 'Closed (Enlightened)', 'Diamond - Epic', 'Discerning - Blue', 'Discerning - Golden', 'Discerning - Gray', 'Discerning - Green', 'Discerning - Purple', 'Discerning - Red', 'Discerning - Skeleton', 'Discerning - White', 'Discerning - Yellow', 'Fire - Epic', 'Fire - Ruby', 'Glitch 1', 'Glitch 2', 'Glitch 3', 'Glitch 4', 'Glitch 5', 'Glitch 6', 'Heart - Epic', 'Moon - Epic', 'Open (Cosmic)', 'Open (Enlightened)', 'Open (Jade)', 'Open - Adorable', 'Open - Blue', 'Open - Diamond', 'Open - Enchanted', 'Open - Fire', 'Open - Golden', 'Open - Gray', 'Open - Green', 'Open - Moon', 'Open - Purple', 'Open - Rainbow', 'Open - Red', 'Open - Robot', 'Open - Ruby', 'Open - Skeleton', 'Open - White', 'Open - Yellow', 'Rainbow - Epic', 'Relaxed (Enlightened)', 'Relaxed (Jade)', 'Relaxed - Blue', 'Relaxed - Golden', 'Relaxed - Gray', 'Relaxed - Green', 'Relaxed - Purple', 'Relaxed - Red', 'Relaxed - Ruby', 'Relaxed - Skeleton', 'Relaxed - White', 'Relaxed - Yellow', 'Side-eye - Blue', 'Side-eye - Golden', 'Side-eye - Gray', 'Side-eye - Green', 'Side-eye - Purple', 'Side-eye - Red', 'Side-eye - White', 'Side-eye - Yellow'],
    eyewears: ['Blockers', 'Heart Glasses', '3D Glasses', 'Aviators', 'Big Tech', 'Black-rimmed Glasses', 'Eyepatch', 'Gazelles', 'Half-moon Spectacles', 'Jobs Glasses', 'Monocle (Jade)', 'Monocle', 'None', 'Rose-Colored Glasses', 'Sunglasses', 'Visor (Jade)', 'Visor (Diamond)', 'Visor (Gold)', 'Visor'],
    headwears: ['Baker Boy', 'Beret', 'Head Wrap', 'Idea', 'Laurel Wreath', 'Miner', 'Great Horned Parliament Mask', 'Parliament Mask', 'Raptor Parliament Mask', 'Royal Parliament Mask', 'Silver Parliament Mask', 'Parliament Mask (Jade)', 'Rainbow', 'Top Hat', 'Unicorn Horn', 'Water Sprite', "Leprechaun's Hat", 'Police Hat', 'Mushroom Cap', 'Biker Hat', 'Trucker Hat', 'Skull Cap', "Blue Backwards Hat", "Green Backwards Hat", "Aviator's Cap", 'Backwards Hat', 'Bandana', 'Beanie', 'Bow', 'Bucket Hat', "Captain's Cap", 'Chromie', 'Cowboy Hat', 'Crescent Talisman (Jade)', 'Crescent Talisman', 'Dancing Flame (Enlightened Variant)', 'Dancing Flame (Jade)', 'Dancing Flame', 'Diamond (Jade)', 'Diamond', 'Durag', 'Fire', 'Flower', 'Forest Ranger', 'Grail', 'Gremplin', 'Halo (Enlightened Variant)', 'Halo (Jade)', 'Halo', 'Headband', 'Headphones', "Hero's Cap", 'Karate Band', 'Lincoln', 'Mohawk (Green)', 'Mohawk (Jade)', 'Mohawk (Pink)', 'Moon Hat', 'None', "Pirate's Hat", "Queen's Crown", 'Raincloud', 'Rubber Duck', 'Skully (Jade)', 'Skully', 'Space Helmet', 'Tiara', 'Tiny Crown (Enlightened)', 'Tiny Crown (Jade)', 'Tiny Crown', 'Unicorn Horn (Jade)', "Pink Witch's Hat", "Blue Witch's Hat", "Witch's Hat", "Wizard's Hat (Jade)", "Wizard's Hat"],
    outerwears: ['Hooded Cloak', 'Spiked Collar', 'Bomber Jacket', 'Diamond Necklace', "Diamond Jacket", 'Gold Chain', "Gold Jacket", "Hero's Tunic", "Pink Hoodie Down", "Red Hoodie Down", "Green Hoodie Down", "Black Hoodie Down", 'Hoodie Down', 'Pink Hoodie', 'Red Hoodie', 'Green Hoodie', 'Hoodie', 'Blue Hoodie', 'Jean Jacket', 'None', 'Punk Jacket'],
};

export const generateRandomMoonbird = (): MoonbirdConfig => {
  const randomKey = (layer: string[]) => layer[Math.floor(Math.random() * layer.length)];

  return {
    background: randomKey(layerOptions.backgrounds),
    body: randomKey(layerOptions.bodies),
    beak: randomKey(layerOptions.beaks),
    eyes: randomKey(layerOptions.eyes),
    eyewear: randomKey(layerOptions.eyewears),
    headwear: randomKey(layerOptions.headwears),
    outerwear: randomKey(layerOptions.outerwears),
  };
};
